### ISSUE TITLE
Automate workflows for GitHub issue triage

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/community#11]
Our team has been experimenting with workflows around GitHub issue management. See [google doc](https://docs.google.com/document/d/1DfRf9WRPpAjb0twg4DNtSOKHEnlyxGiLeOZkGB5NH-E/edit?usp=sharing) with our work in progress.

This issue is about automating that workflow once it has been established. Some ideas for how we will automate are (could be some combination of these):

* Maintain our own GitHub actions script: https://github.com/actions/github-script
* Use a third party action to label new issues: https://github.com/marketplace/actions/simple-issue-labeler
* Use a third party action to label inactive issues as stale: https://github.com/marketplace/actions/close-stale-issues
  * Potentially not as useful in its current form as we'd want to configure multiple values for `exempt-issue-label`
* Use dispatches:
  * `buildpacks/community`  could have `on: dispatch`
  * Every repo could have a single line `on: <issue created ...>` dispatch to community

It may make sense to block this work on https://github.com/buildpacks/rfcs/pull/53 so that we have consensus on how labels are managed.

**Comment by dfreilich** [comment]
@natalieparellano Now that https://github.com/buildpacks/rfcs/pull/53/ has been merged, should we prioritize this?

**Comment by jromero** [comment]
Since the inception of this issue, sub-teams have taken on the responsibility of maintaining their own set of repos with their own processes on how to follow-up with stale issues. Closing as it seems no longer relevant.
