### ISSUE TITLE
End users: ADOPTERS.md

### ISSUE THREAD

**Issue by zmackie** [buildpacks/community#12]
Are you using CNB in production?
Let us know about your use case by either commenting in this issue or opening a pull request adding yourself to `ADOPTERS.md`.

**Comment by pclalv** [comment]
my employer, [Greenhouse](https://github.com/grnhse/), uses CNB in production. we run our own platform and have written our own buildpacks.

**Comment by abarke** [comment]
We have been prototyping CNB/Pack for local development at [FactSet](https://www.factset.com). We use heroku buildpacks and wanted a way to unify the environment for local development. `pack` was a perfect solution. It allowed us to build a docker container for local development with very little configuration changes while setting up a near identical environment to production. CI in Jenkins using `pack` is the next step to a truely uniform pipeline 🚀

By the way... Microsoft are also using `pack` and bundling it with their [Azure CLI](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-pack-build) in a developer preview.

**Comment by jromero** [comment]
FYI: We'll be moving this to a [discussion](https://github.com/buildpacks/community/discussions).

**Comment by samj1912** [comment]
Closing this since we moved to a discussion instead.
