### ISSUE TITLE
Clarify where are located the buildpacks on Github

### ISSUE THREAD

**Issue by collimarco** [buildpacks/community#143]
From your official website it seems impossible to find the repositories of the buildpacks on Github.

Can you please clarify where are they located?

For example, take a Rails app that I want to pack, how can I get a list of all the buildpacks (Heroku, Pivotal, etc.) and their repo on Github (i.e. Github link)?

**Comment by dfreilich** [comment]
Hey @collimarco , sorry that you found it hard to find! The Buildpacks project doesn't maintain buildpacks - instead, we support vendors who offer them, and register them in the [Buildpacks Registry](https://registry.buildpacks.io/). We do have a link to it on the website, but this is valuable feedback that we could perhaps discovering/the relevance of the registry a clearer point. (cc @buildpacks/learning-contributors )

One other place users can discover buildpacks/builders is by running `pack builder suggest`, which should return a list of builders. By then inspecting them (`pack builder inspect <builder-name>`), that should give a homepage of the Builder/buildpack, which will often be a Github link. That is a more circutuous route, though, and we'd generally recommend that users discover Buildpacks by selecting the Github logo on the registry pages for buildpacks.

**Comment by collimarco** [comment]
Thanks for the reply!

Two notes:
- IMHO the Github icon is not very visible in the registry (I didn't see it at first)
- And, more important, Heroku buildpacks don't have any link to the Github repos

**Comment by jkutner** [comment]
Yea, I agree that Github icon is not noticeable.
