### ISSUE TITLE
Clarify why a Procfile is useful inside a Buildpacks

### ISSUE THREAD

**Issue by collimarco** [buildpacks/community#146]
Is there any difference between the following two cases?

CASE 1

- Create a buildpack without Procfile
- then run `launcher` `my command`

CASE 2

- Define a Procfile with `procname: my command`
- then run `procname`

I need to run the final images inside Kubernetes and I don't see any difference between CASE 1 and CASE 2... **Is there any substantial difference?** Is there any security difference?

Should I always specify a Procfile (CASE 2) or I can just use `launcher` with any command (CASE 1)?

**Comment by jromero** [comment]
This is an interesting question. As an individual that doesn't necessarily use Procfiles, I'll let others try to answer this one. 

The only thing I will say, is that Profiles are not a "Buildpacks" concept although various buildpack providers use them (Google, Heroku, Paketo). It may be worth reaching out to the community of the buildpack provider you are using.

**Comment by collimarco** [comment]
Finally we decided to use **CASE 1**: this is because it is supported by all Buildpacks, and thus more standard, whereas Procfile is not necessarily supported by all Buildpacks providers. Also you can use the Docker image for dynamic commands not defined at build time.

In any case I would still be curious to know if there are any advantages in using **CASE 2** (Procfile).

**Comment by jromero** [comment]
@jkutner - I believe you may have some background on this topic. Care to chime in?

**Comment by jkutner** [comment]
@collimarco `Procfile` is useful in Case 2 only in that it helps encapsulate what might be a complicated or ugly launch command. It's also helpful when you need to codify many different commands that might be used to run a container from a given image (rather than just memorizing a bunch of `launcher my command` patterns)

It exists mainly as a convenience for people who've been using it since before CNB.

**Comment by collimarco** [comment]
@jkutner So the `Procfile`, in the context of CNB, is only for convenience, but without any actual difference or security implication compared to `launcher`. And basically I can use one or the other without major differences. Ok, perfect!

**Comment by jromero** [comment]
I'm considering this resolved. Feel free to re-open if that's not true.
