### ISSUE TITLE
Is there a conversion error with timezone ET to UTC in README.md?

### ISSUE THREAD

**Issue by ajdergute** [buildpacks/community#152]
I'm not sure, but IMHO all UTC times mentioned in this README.md should be +1 hour.

For example
https://github.com/buildpacks/community/blob/main/README.md?plain=1#L66
this is actually 19:00 UTC.

Am I right?

If so please note: https://github.com/buildpacks/community/pull/153

**Comment by samj1912** [comment]
Fixed in #154
