### ISSUE TITLE
Add Contributors Guide

### ISSUE THREAD

**Issue by hone** [buildpacks/community#4]

**Comment by dfreilich** [comment]
@hone Do we still need one here, given that we have in [pack](https://github.com/buildpacks/pack/blob/master/CONTRIBUTING.md), and hopefully one in lifecycle?

**Comment by hone** [comment]
It definitely isn't as necessary (or as high priority), but are we going to have the same for all of our repos (we probably should). It still might be nice to have a general one so we aren't duping the contents all over the place.
