### ISSUE TITLE
Use https://allcontributors.org/

### ISSUE THREAD

**Issue by zmackie** [buildpacks/community#5]
Use https://allcontributors.org/ to recognize our contributors

**Comment by jromero** [comment]
#### Allcontributors

Pros:
-  Can recognize individual that don't commit but help in other ways.

Cons:
- Table is multiple contrib images which takes a while to render
- Manual process - need to tell the bot to add somebody


####  github-contributors-list
I've seen something similar to https://github.com/mgechev/github-contributors-list being used in which a single image is generated and randomized periodically.

Pros:
- Can be automated
- Single image (faster)

Cons:
- Recognizes only individuals that contribute code

**Comment by dfreilich** [comment]
@jromero This definitely looks interesting. I'd be down for adding it in.

**Comment by hone** [comment]
@jromero is there a way we can do both? What I mean by that can we use `github-contributors-list` plus some manual way to insert people in?

**Comment by jromero** [comment]
Is this still desired? Since the creation of this issue we now acknowledge contributors on release notes. Is that sufficient?
